.TH grass57 1 "October 12, 2004" "grass57"

.SH NAME
grass57 \- geographic information system

.SH SYNOPSIS
.B grass57
.RI "[-text | -tcltk | -gui] [[[<GISDBASE>/]<LOCATION_NAME>/]<MAPSET>]"
.br

.SH DESCRIPTION
This  manual  page  documents  briefly  the
.B grass57
command.  This manual page was written for the Debian distribution because the original program does not  have a manual page.
.PP
GRASS GIS (Geographic Resources Analysis Support System) is a Geographical Information System (GIS) with raster, topological vector, image processing, and graphics production functionality.

.SH OPTIONS
.TP
.B \-h \-help \-\-help
Print help and usage information.
.TP
.B \-text
Use the text-based interface and set it as the default.
.TP
.B \-tcltk \-gui
Use the Tcl/Tk based graphical user interface and set it as the default.

.SH ENVIRONMENT
.TP
GRASS_TCLSH
Set the tclsh shell name to override 'tclsh'.
.TP
GRASS_WISH
Set the wish shell name to override 'wish'.
.TP
GRASS_HTML_BROWSER
Set the html browser for help pages.
.TP
GRASS_ADDON_PATH
Set additional path(s) to local GRASS modules.

.SH SEE ALSO
There is documentation in HTML format at /usr/lib/grass57/docs/html/index.html
.PP
There are also docs and tutorials online at http://grass.itc.it/gdp/

.SH AUTHOR
This  manual  page  was  written  by  Steve Halasz <debian@adkgis.org>, for the Debian project (but may be used by others).

