# This is a generated file.\n
menustrings_menudata.LayerManagerMenuData = [
    _('&File'),
    _('Workspace'),
    _('New'),
    _('Create new workspace'),
    _('Open'),
    _('Load workspace from file'),
    _('Save'),
    _('Save workspace'),
    _('Save as'),
    _('Save workspace to file'),
    _('Close'),
    _('Close workspace file'),
    _('Load GRC file (Tcl/Tk GUI)'),
    _('Load map layers from GRC file to layer tree'),
    _('Map display'),
    _('Add raster'),
    _('Add raster map layer to current display'),
    _('Add vector'),
    _('Add vector map layer to current display'),
    _('Add multiple rasters or vectors'),
    _('Add multiple raster or vector map layers to current display'),
    _('Add web service layer'),
    _('Add web service layer'),
    _('New map display window'),
    _('Open new map display window'),
    _('Close current map display window'),
    _('Close current map display window'),
    _('Close all open map display windows'),
    _('Close all open map display windows'),
    _('Import raster data'),
    _('Common formats import'),
    _('Imports raster data into a GRASS raster map using GDAL library.'),
    _('Import of common formats with reprojection'),
    _('Imports raster data into a GRASS raster map using GDAL library and reprojects on the fly.'),
    _('ASCII x,y,z point import and gridding'),
    _('ASCII grid import'),
    _('ASCII polygons, lines, and point import'),
    _('Raw binary array import'),
    _('GRIDATB.FOR import'),
    _('Matlab 2D array import'),
    _('PNG import'),
    _('SPOT NDVI import'),
    _('Imports SPOT VGT NDVI data into a raster map.'),
    _('SRTM HGT import'),
    _('Imports SRTM HGT files into raster map.'),
    _('Terra ASTER HDF import'),
    _('Georeference, rectify, and import Terra-ASTER imagery and relative DEMs using gdalwarp.'),
    _('LAS LiDAR points import'),
    _('Unpack raster map'),
    _('Imports a raster map as GRASS GIS specific archive file (packed with r.pack)'),
    _('Reproject raster map from different GRASS location'),
    _('Import vector data'),
    _('Common import formats'),
    _('Imports vector data into a GRASS vector map using OGR library.'),
    _('Import of common formats with reprojection'),
    _('Imports vector data into a GRASS vector map using OGR library and reprojects on the fly.'),
    _('ASCII points or GRASS ASCII format'),
    _('ASCII points as a vector lines'),
    _('Imports ASCII x,y[,z] coordinates as a series of lines.'),
    _('DXF import'),
    _('Converts files in DXF format to GRASS vector map format.'),
    _('WFS'),
    _('Imports GetFeature from a WFS server.'),
    _('ESRI e00 import'),
    _('Imports E00 file into a vector map.'),
    _('Geonames import'),
    _('Imports geonames.org country files into a vector points map.'),
    _('Matlab array or Mapgen format import'),
    _('Imports Mapgen or Matlab-ASCII vector maps into GRASS.'),
    _('LAS LiDAR points import'),
    _('Unpack vector map'),
    _('Imports a vector map as GRASS GIS specific archive file (packed with v.pack)'),
    _('Reproject vector map from different GRASS location'),
    _('Import 3D raster data'),
    _('ASCII 3D import'),
    _('Raw binary array 3D import'),
    _('Vis5D import'),
    _('Import database table'),
    _('Common import formats'),
    _('Imports attribute tables in various formats.'),
    _('Export raster map'),
    _('Common export formats'),
    _('ASCII grid export'),
    _('ASCII x,y,z points export'),
    _('Exports a raster map to a text file as x,y,z values based on cell centers.'),
    _('GRIDATB.FOR export'),
    _('Matlab 2D array export'),
    _('Raw binary array export'),
    _('MPEG-1 export'),
    _('PNG export'),
    _('PPM export'),
    _('PPM from RGB export'),
    _('POV-Ray export'),
    _('VRML export'),
    _('VTK export'),
    _('Pack raster map'),
    _('Exports a raster map as GRASS GIS specific archive file'),
    _('Export vector map'),
    _('Common export formats'),
    _('ASCII points or GRASS ASCII vector export'),
    _('DXF export'),
    _('PostGIS export'),
    _('POV-Ray export'),
    _('SVG export'),
    _('VTK export'),
    _('Pack vector map'),
    _('Exports a vector map as GRASS GIS specific archive file'),
    _('Export 3D raster maps'),
    _('ASCII 3D export'),
    _('Raw binary array 3D export'),
    _('Vis5D export'),
    _('VTK export'),
    _('Export database table'),
    _('Common export formats'),
    _('Exports attribute tables into various formats.'),
    _('Link external data'),
    _('Link external raster data'),
    _('Link GDAL supported raster data as a pseudo GRASS raster map layer.'),
    _('Link external vector data'),
    _('Creates a new pseudo-vector map as a link to an OGR-supported layer.'),
    _('Output format for raster data'),
    _('Output format for vector data'),
    _('Defines vector output format utilizing OGR library.'),
    _('Manage maps'),
    _('Copy'),
    _('List'),
    _('Rename'),
    _('Delete'),
    _('Map type conversions'),
    _('Raster to vector'),
    _('Raster series to 3D raster'),
    _('Raster 2.5D to 3D raster'),
    _('Vector to raster'),
    _('Vector to 3D raster'),
    _('2D vector to 3D vector'),
    _('3D raster to raster series'),
    _('Georectify'),
    _('Manage Ground Control Points for Georectification'),
    _('Graphical modeler'),
    _('Launch Graphical modeler'),
    _('Run model'),
    _('Run model prepared by Graphical modeler'),
    _('3D image rendering'),
    _('Animation tool'),
    _('Launch animation tool.'),
    _('Bearing/distance to coordinates'),
    _('A simple utility for converting bearing and distance measurements to coordinates and vice versa. It assumes a cartesian coordinate system'),
    _('Cartographic Composer'),
    _('Launch Cartographic Composer'),
    _('Map Swipe'),
    _('Launch Map Swipe'),
    _('Launch script'),
    _('Launches script file.'),
    _('Close GUI'),
    _('Quit wxGUI session.'),
    _('Quit GRASS GIS'),
    _('Quit wxGUI session and exit GRASS shell.'),
    _('&Settings'),
    _('Region'),
    _('Display region'),
    _('Manages the boundary definitions for the geographic region.'),
    _('Set region'),
    _('GRASS working environment'),
    _('Mapset access'),
    _('Set/unset access to other mapsets in current location'),
    _('User access'),
    _('Controls access to the current mapset for other users on the system. If no option given, prints current status.'),
    _('Change working environment'),
    _('Changes/reports current mapset. Optionally create new mapset or list available mapsets in given location.'),
    _('Change location and mapset'),
    _('Change current location and mapset.'),
    _('Change mapset'),
    _('Change current mapset.'),
    _('Change working directory'),
    _('Change working directory'),
    _('Show settings'),
    _("Outputs and modifies the user's current GRASS variable settings."),
    _('Change settings'),
    _("Outputs and modifies the user's current GRASS variable settings. Prints all defined GRASS variables if no option is given."),
    _('Create new location'),
    _('Launches location wizard to create new GRASS location.'),
    _('Create new mapset'),
    _('Creates new mapset in the current location, changes current mapset.'),
    _('Version and copyright'),
    _('Displays version and copyright information.'),
    _('Map projections'),
    _('Display map projection'),
    _('Converts co-ordinate system descriptions (i.e. projection information) between various formats (including GRASS format).'),
    _('Manage projections'),
    _('Prints or modifies GRASS projection information files (in various co-ordinate system descriptions). Can also be used to create new GRASS locations.'),
    _('Convert coordinates'),
    _('Converts coordinates from one projection to another (cs2cs frontend).'),
    _('Addons extensions'),
    _('Install extension from addons'),
    _('Installs new extension from GRASS AddOns SVN repository.'),
    _('Manage installed extension'),
    _('Updates or removes installed GRASS AddOns extension(s).'),
    _('Preferences'),
    _('User GUI preferences (display font, commands, digitizer, etc.)'),
    _('&Raster'),
    _('Develop raster map'),
    _('Compress/decompress'),
    _('Region boundaries'),
    _('Manage NULL values'),
    _('Quantization'),
    _('Timestamp'),
    _('Resample using aggregate statistics'),
    _('Resample using multiple methods'),
    _('Resample using nearest neighbor'),
    _('Resample using spline tension'),
    _('Resample using bspline'),
    _('Resample using analytic kernel'),
    _('Support file maintenance'),
    _('Update map statistics'),
    _('Reproject raster map from different GRASS location'),
    _('Tiling'),
    _('Produces tilings of the source projection for use in the destination region and projection.'),
    _('Manage colors'),
    _('Color tables'),
    _('Color tables (stddev)'),
    _("Sets color rules based on stddev from a raster map's mean value."),
    _('Manage color rules interactively'),
    _('Interactive management of raster color tables.'),
    _('Export color table'),
    _('Blend 2 color rasters'),
    _('Blends color components of two raster maps by a given ratio.'),
    _('Create RGB'),
    _('RGB to HIS'),
    _('Query raster maps'),
    _('Query values by coordinates'),
    _('Query colors by value'),
    _('Map type conversions'),
    _('Raster to vector'),
    _('Raster series to 3D raster'),
    _('Raster 2.5D to 3D raster'),
    _('Raster buffers and distance'),
    _('Buffer rasters'),
    _('Concentric circles'),
    _('Closest points'),
    _('Grow by one cell'),
    _('Generates a raster map layer with contiguous areas grown by one cell.'),
    _('Distance to features'),
    _('Mask'),
    _('Creates a MASK for limiting raster operation.'),
    _('Raster map calculator'),
    _('Raster map calculator'),
    _('Neighborhood analysis'),
    _('Moving window'),
    _('Neighborhood points'),
    _('Overlay rasters'),
    _('Cross product'),
    _('Patch raster maps'),
    _('Raster series aggregation'),
    _('Raster series accumulation'),
    _('Statistical overlay'),
    _('Quantiles overlay'),
    _('Solar radiance and shadows'),
    _('LatLong map'),
    _('Solar irradiance and irradiation'),
    _('Shadows map'),
    _('Sunshine hours and solar angles'),
    _('Terrain analysis'),
    _('Generate contour lines'),
    _('Cost surface'),
    _('Cumulative movement costs'),
    _('Least cost route or flow'),
    _('Compute shaded relief'),
    _('Apply shade to raster'),
    _('Drapes a color raster over an shaded relief or aspect map.'),
    _('Slope and aspect'),
    _('Terrain parameters'),
    _('Textural features'),
    _('Visibility'),
    _('Distance to features'),
    _('Horizon angle'),
    _('Transform features'),
    _('Clump'),
    _('Grow'),
    _('Generates a raster map layer with contiguous areas grown by one cell.'),
    _('Thin'),
    _('Hydrologic modeling'),
    _('Carve stream channels'),
    _('Fill lake'),
    _('Depressionless map and flowlines'),
    _('Flow accumulation'),
    _('Flow lines'),
    _('Watershed analysis'),
    _('Watershed subbasins'),
    _('Watershed basin creation'),
    _('Extraction of stream networks'),
    _('SIMWE Overland flow modeling'),
    _('SIMWE Sediment flux modeling'),
    _('Topographic index map'),
    _('TOPMODEL simulation'),
    _('USLE K-factor'),
    _('USLE R-factor'),
    _('Groundwater modeling'),
    _('Groundwater flow'),
    _('Groundwater solute transport'),
    _('Landscape patch analysis'),
    _('Set up sampling and analysis framework'),
    _("Configuration editor for r.li.'index'"),
    _('Edge density'),
    _('Contrast weighted edge density'),
    _('Patch area mean'),
    _('Patch area range'),
    _('Patch area Std Dev'),
    _('Patch area Coeff Var'),
    _('Patch density'),
    _('Patch number'),
    _("Dominance's diversity"),
    _("Shannon's diversity"),
    _("Simpson's diversity"),
    _('Richness'),
    _('Shape index'),
    _('Wildfire modeling'),
    _('Rate of spread'),
    _('Least-cost spread paths'),
    _('Anisotropic spread simulation'),
    _('Change category values and labels'),
    _('Manage category information'),
    _('Interactively edit category values'),
    _('Edits cell values in a raster map.'),
    _('Reclassify by size'),
    _('Reclasses a raster map greater or less than user specified area size (in hectares).'),
    _('Reclassify'),
    _('Recode'),
    _('Rescale'),
    _('Rescale with histogram'),
    _('Generate random cells'),
    _('Random cells'),
    _('Random cells and vector points'),
    _('Generate surfaces'),
    _('Fractal surface'),
    _('Gaussian kernel density surface'),
    _('Gaussian deviates surface'),
    _('Plane'),
    _('Creates raster plane map given dip (inclination), aspect (azimuth) and one point.'),
    _('Random deviates surface'),
    _('Random surface with spatial dependence'),
    _('Interpolate surfaces'),
    _('Bilinear and bicubic from vector points'),
    _('IDW from raster points'),
    _('IDW from vector points'),
    _('Raster contours'),
    _('Regularized spline tension'),
    _('Raster series interpolation'),
    _('Ordinary or block kriging'),
    _('Performs ordinary or block kriging.'),
    _('Fill NULL cells'),
    _('Fills no-data areas in raster maps using spline interpolation.'),
    _('Reports and statistics'),
    _('Basic raster metadata'),
    _('Manage category information'),
    _('General statistics'),
    _('Quantiles for large data sets'),
    _('Range of category values'),
    _('Sum area by raster map and category'),
    _('Statistics for clumped cells'),
    _('Total corrected area'),
    _('Univariate raster statistics'),
    _('Sample transects'),
    _('Sample transects (bearing/distance)'),
    _('Covariance/correlation'),
    _('Linear regression'),
    _('Multiple regression'),
    _('Mutual category occurrences'),
    _('&Vector'),
    _('Develop vector map'),
    _('Create new vector map'),
    _('Create new empty vector map'),
    _('Edit vector map (non-interactively)'),
    _('Convert object types'),
    _('Parallel lines'),
    _('Dissolve boundaries'),
    _('Dissolves boundaries between adjacent areas sharing a common category number or attribute.'),
    _('Create 3D vector over raster'),
    _('Extrude 3D vector map'),
    _('Create labels'),
    _('Reposition vector map'),
    _('Rectify vector map'),
    _('Reproject vector map from different GRASS location'),
    _('Support file maintenance'),
    _('Topology maintenance'),
    _('Create or rebuild topology'),
    _('Rebuild topology on all vector maps'),
    _('Rebuilds topology on all vector maps in the current mapset.'),
    _('Build polylines'),
    _('Split lines'),
    _('Split polylines'),
    _('Clean vector map'),
    _('Toolset for cleaning topology of vector map.'),
    _('Smooth or simplify'),
    _('Add centroids'),
    _('Adds missing centroids to closed boundaries.'),
    _('Manage colors'),
    _('Color tables'),
    _('Manage color rules interactively'),
    _('Interactive management of vector color tables.'),
    _('Export color table'),
    _('Query vector map'),
    _('Query with coordinate(s)'),
    _('Query vector attribute data'),
    _('Feature selection'),
    _('Select by attributes'),
    _('Select by another map'),
    _('Map type conversions'),
    _('Vector to raster'),
    _('Vector to 3D raster'),
    _('2D vector to 3D vector'),
    _('Buffer vectors'),
    _('Lidar analysis'),
    _('Identify and remove outliers'),
    _('Detect edges'),
    _('Detect interiors'),
    _('Correct and reclassify objects'),
    _('Linear referencing'),
    _('Create LRS'),
    _('Create stationing'),
    _('Create points/segments'),
    _('Find line id and offset'),
    _('Nearest features'),
    _('Network analysis'),
    _('Vector network analysis tool'),
    _('Tool for interactive vector network analysis.'),
    _('Network preparation'),
    _('Allocate subnets'),
    _('Split net'),
    _('Shortest path'),
    _('Shortest path for sets of features'),
    _('Shortest path using timetables'),
    _('Shortest path for all pairs'),
    _('Visibility network'),
    _('Bridges and articulation points'),
    _('Maximum flow'),
    _('Vertex connectivity'),
    _('Components'),
    _('Centrality'),
    _('Steiner tree'),
    _('Minimum spanning tree'),
    _('Traveling salesman analysis'),
    _('Overlay vector maps'),
    _('Overlay vector maps'),
    _('Patch vector maps'),
    _('Manage categories'),
    _('Change or report categories'),
    _('Reclassify'),
    _('Update attributes'),
    _('Update area attributes from raster'),
    _('Calculates univariate statistics from a raster map based on a vector map and uploads statistics to new attribute columns.'),
    _('Update area attributes from vector'),
    _('Update point attributes from areas'),
    _('Uploads vector values at positions of vector points to the table.'),
    _('Update database values from vector'),
    _('Sample raster maps at point locations'),
    _('Sample raster neighborhood around points'),
    _('Generate area for current region'),
    _('Generate areas from points'),
    _('Convex hull'),
    _('Delaunay triangles'),
    _('Voronoi diagram/Thiessen polygons'),
    _('Generate grid'),
    _('Generate points'),
    _('Generate from database'),
    _('Generate points along lines'),
    _('Generate random points'),
    _('Perturb points'),
    _('Remove outliers in point sets'),
    _('Test/training point sets'),
    _('Reports and statistics'),
    _('Basic vector metadata'),
    _('Classify attribute data'),
    _('Report topology by category'),
    _('Reports geometry statistics for vector maps.'),
    _('Univariate attribute statistics for points'),
    _('Univariate statistics for attribute columns'),
    _('Calculates univariate statistics on selected table column for a GRASS vector map.'),
    _('Quadrat indices'),
    _('Test normality'),
    _('&Imagery'),
    _('Develop images and groups'),
    _('Create/edit group'),
    _('Creates, edits, and lists groups of imagery files.'),
    _('Target group'),
    _('Mosaic images'),
    _('Mosaics several images and extends colormap.'),
    _('Manage image colors'),
    _('Color balance for RGB'),
    _('Performs auto-balancing of colors for RGB images.'),
    _('HIS to RGB'),
    _('RGB to HIS'),
    _('Rectify image or raster'),
    _('Histogram'),
    _('Generate histogram of image'),
    _('Spectral response'),
    _('Displays spectral response at user specified locations in group or images.'),
    _('Pan sharpening'),
    _('Image fusion algorithms to sharpen multispectral with high-res panchromatic channels'),
    _('Classify image'),
    _('Clustering input for unsupervised classification'),
    _('Input for supervised MLC'),
    _('Maximum likelihood classification (MLC)'),
    _('Interactive input for supervised classification'),
    _('Generates spectral signatures by allowing the user to outline training areas.'),
    _('Input for supervised SMAP'),
    _('Sequential maximum a posteriori classification (SMAP)'),
    _('Object segmentation'),
    _('Filter image'),
    _('Edge detection'),
    _('Matrix/convolving filter'),
    _('Transform image'),
    _('Canonical correlation'),
    _('Principal components'),
    _('Fast Fourier'),
    _('Inverse Fast Fourier'),
    _('Satellite images tools'),
    _('Aster DN to radiance/reflectance'),
    _('Landsat DN to radiance/reflectance'),
    _('Landsat cloud cover assessment'),
    _('Modis quality control'),
    _('Atmospheric correction'),
    _('Topographic correction'),
    _('Satellite images products'),
    _('Vegetation indices'),
    _('Tasseled cap vegetation index'),
    _('Performs Tasseled Cap (Kauth Thomas) transformation.'),
    _('Albedo'),
    _('Emissivity'),
    _('Biomass growth'),
    _('Evapotranspiration calculation'),
    _('Instantaneaous Net Radiation'),
    _('Soil heat flux'),
    _('Sensible heat flux'),
    _('Evaporative fraction'),
    _('Actual Evapotranspiration'),
    _('Temporal integration of ETa'),
    _('Hargreaves methods Evapotranspiration'),
    _('Penman-Monteith Evapotranspiration'),
    _('Priestley-Taylor Evapotranspiration'),
    _('Reports and statistics'),
    _('Kappa analysis'),
    _('OIF for LandSat TM'),
    _('Calculates Optimum-Index-Factor table for spectral bands'),
    _('3D r&aster'),
    _('Develop 3D raster map'),
    _('Manage 3D NULL values'),
    _('Manage timestamp'),
    _('Print/add/remove a timestamp for a 3D raster map'),
    _('Map type conversions'),
    _('3D rasters to raster series'),
    _('3D color tables'),
    _('Export 3D color table'),
    _('3D mask'),
    _('3D raster map calculator'),
    _('3D raster map calculator'),
    _('Cross section'),
    _('Groundwater modeling'),
    _('Interpolate 3D raster from points'),
    _('Reports and Statistics'),
    _('Basic 3D raster metadata'),
    _('3D raster statistics'),
    _('Univariate statistics for 3D rasters'),
    _('&Database'),
    _('Database information'),
    _('List databases'),
    _('Lists all databases for a given driver and location.'),
    _('List drivers'),
    _('Lists all database drivers.'),
    _('List tables'),
    _('Lists all tables for a given database.'),
    _('Describe table'),
    _('Describes a table in detail.'),
    _('List columns'),
    _('List all columns for a given table.'),
    _('Manage databases'),
    _('Connect'),
    _('Prints/sets general DB connection for current mapset.'),
    _('Login'),
    _('Sets user/password for DB driver/database.'),
    _('Create database'),
    _('Creates an empty database.'),
    _('Drop database'),
    _('Removes an existing database.'),
    _('Drop table'),
    _('Drops an attribute table.'),
    _('Copy table'),
    _("Copy a table. Either 'from_table' (optionally with 'where') can be used or 'select' option, but not 'from_table' and 'select' at the same time."),
    _('Drop column'),
    _('Drops a column from selected attribute table.'),
    _('Test'),
    _('Test database driver, database must exist and set by db.connect.'),
    _('Query'),
    _('Query any table'),
    _('Selects data from attribute table. Performs SQL query statement(s).'),
    _('Query vector attribute data'),
    _('SQL statement'),
    _("Executes any SQL statement. For SELECT statements use 'db.select'."),
    _('Vector database connections'),
    _('New table'),
    _('Creates and connects a new attribute table to a given layer of an existing vector map.'),
    _('Remove table'),
    _('Removes existing attribute table of a vector map.'),
    _('Join table'),
    _('Joins a database table to a vector map table.'),
    _('Add columns'),
    _('Adds one or more columns to the attribute table connected to a given vector map.'),
    _('Drop column'),
    _('Drops a column from the attribute table connected to a given vector map.'),
    _('Rename column'),
    _('Renames a column in the attribute table connected to a given vector map.'),
    _('Change values'),
    _('Updates a column in the attribute table connected to a vector map.'),
    _('Drop row'),
    _('Removes a vector feature from a vector map through attribute selection.'),
    _('Reconnect vectors to database'),
    _('Reconnects attribute tables for all vector maps from the current mapset to a new database.'),
    _('Set vector map - database connection'),
    _('&Temporal'),
    _('Manage datasets'),
    _('Create'),
    _('Rename'),
    _('Remove'),
    _('Update metadata'),
    _('Merge'),
    _('Temporally shift'),
    _('Snap maps of dataset'),
    _('List'),
    _('Manage maps in datasets'),
    _('Register maps in datasets'),
    _('Unregister maps from datasets'),
    _('List raster dataset maps'),
    _('List vector dataset maps'),
    _('List 3D raster dataset maps'),
    _('Import'),
    _('Import raster dataset'),
    _('Import vector dataset'),
    _('Export'),
    _('Export raster dataset'),
    _('Export raster dataset as VTK time series'),
    _('Export vector dataset'),
    _('Convert raster dataset to 3D raster'),
    _('Extraction'),
    _('Extract subset of raster dataset'),
    _('Extract subset of vector dataset'),
    _('Extract subset of 3D raster dataset'),
    _('Query vector dataset attribute data'),
    _('Raster dataset color table'),
    _('Raster calculations'),
    _('3D raster calculations'),
    _('Interpolate gaps in raster datasets'),
    _('Aggregation'),
    _('Neighborhood analysis in raster dataset'),
    _('Aggregation in raster datasets'),
    _('Temporal aggregation'),
    _('Temporal aggregation by dataset'),
    _('Sampling'),
    _('Temporal sampling'),
    _('Query raster dataset by vector points dataset'),
    _('Observe specific locations in raster dataset'),
    _('Reports and statistics'),
    _('Space time datasets metadata'),
    _('Univariate raster dataset statistics'),
    _('Univariate vector dataset statistics'),
    _('Univariate 3D raster dataset statistics'),
    _('Report temporal topology'),
    _('GUI tools'),
    _('Animation tool'),
    _('Launch animation tool.'),
    _('Timeline tool'),
    _('Plot temporal extents.'),
    _('Temporal plot tool'),
    _('Plot temporal values.'),
    _('&Help'),
    _('GRASS help'),
    _('Display the HTML man pages of GRASS GIS'),
    _('GUI help'),
    _('Display the HTML man pages of GRASS GIS'),
    _('About system'),
    _('Prints system information'),
    _('About GRASS GIS'),
    _('About GRASS GIS'),
    '']
menustrings_menudata.LayerManagerModuleTree = [
    _('Import, export and link data'),
    _('Import raster data'),
    _('Common formats import'),
    _('Imports raster data into a GRASS raster map using GDAL library.'),
    _('Import of common formats with reprojection'),
    _('Imports raster data into a GRASS raster map using GDAL library and reprojects on the fly.'),
    _('ASCII x,y,z point import and gridding'),
    _('ASCII grid import'),
    _('ASCII polygons, lines, and point import'),
    _('Raw binary array import'),
    _('GRIDATB.FOR import'),
    _('Matlab 2D array import'),
    _('PNG import'),
    _('SPOT NDVI import'),
    _('Imports SPOT VGT NDVI data into a raster map.'),
    _('SRTM HGT import'),
    _('Imports SRTM HGT files into raster map.'),
    _('Terra ASTER HDF import'),
    _('Georeference, rectify, and import Terra-ASTER imagery and relative DEMs using gdalwarp.'),
    _('LAS LiDAR points import'),
    _('Unpack raster map'),
    _('Imports a raster map as GRASS GIS specific archive file (packed with r.pack)'),
    _('Reproject raster map from different GRASS location'),
    _('Import vector data'),
    _('Common import formats'),
    _('Imports vector data into a GRASS vector map using OGR library.'),
    _('Import of common formats with reprojection'),
    _('Imports vector data into a GRASS vector map using OGR library and reprojects on the fly.'),
    _('ASCII points or GRASS ASCII format'),
    _('ASCII points as a vector lines'),
    _('Imports ASCII x,y[,z] coordinates as a series of lines.'),
    _('DXF import'),
    _('Converts files in DXF format to GRASS vector map format.'),
    _('WFS'),
    _('Imports GetFeature from a WFS server.'),
    _('ESRI e00 import'),
    _('Imports E00 file into a vector map.'),
    _('Geonames import'),
    _('Imports geonames.org country files into a vector points map.'),
    _('Matlab array or Mapgen format import'),
    _('Imports Mapgen or Matlab-ASCII vector maps into GRASS.'),
    _('LAS LiDAR points import'),
    _('Unpack vector map'),
    _('Imports a vector map as GRASS GIS specific archive file (packed with v.pack)'),
    _('Reproject vector map from different GRASS location'),
    _('Import 3D raster data'),
    _('ASCII 3D import'),
    _('Raw binary array 3D import'),
    _('Vis5D import'),
    _('Import database table'),
    _('Common import formats'),
    _('Imports attribute tables in various formats.'),
    _('Export raster map'),
    _('Common export formats'),
    _('ASCII grid export'),
    _('ASCII x,y,z points export'),
    _('Exports a raster map to a text file as x,y,z values based on cell centers.'),
    _('GRIDATB.FOR export'),
    _('Matlab 2D array export'),
    _('Raw binary array export'),
    _('MPEG-1 export'),
    _('PNG export'),
    _('PPM export'),
    _('PPM from RGB export'),
    _('POV-Ray export'),
    _('VRML export'),
    _('VTK export'),
    _('Pack raster map'),
    _('Exports a raster map as GRASS GIS specific archive file'),
    _('Export vector map'),
    _('Common export formats'),
    _('ASCII points or GRASS ASCII vector export'),
    _('DXF export'),
    _('PostGIS export'),
    _('POV-Ray export'),
    _('SVG export'),
    _('VTK export'),
    _('Pack vector map'),
    _('Exports a vector map as GRASS GIS specific archive file'),
    _('Export 3D raster maps'),
    _('ASCII 3D export'),
    _('Raw binary array 3D export'),
    _('Vis5D export'),
    _('VTK export'),
    _('Export database table'),
    _('Common export formats'),
    _('Exports attribute tables into various formats.'),
    _('Link external data'),
    _('Link external raster data'),
    _('Link GDAL supported raster data as a pseudo GRASS raster map layer.'),
    _('Link external vector data'),
    _('Creates a new pseudo-vector map as a link to an OGR-supported layer.'),
    _('Output format for raster data'),
    _('Output format for vector data'),
    _('Defines vector output format utilizing OGR library.'),
    _('Manage maps'),
    _('Copy'),
    _('List'),
    _('Rename'),
    _('Delete'),
    _('&Raster'),
    _('Develop raster map'),
    _('Compress/decompress'),
    _('Region boundaries'),
    _('Manage NULL values'),
    _('Quantization'),
    _('Timestamp'),
    _('Resample using aggregate statistics'),
    _('Resample using multiple methods'),
    _('Resample using nearest neighbor'),
    _('Resample using spline tension'),
    _('Resample using bspline'),
    _('Resample using analytic kernel'),
    _('Support file maintenance'),
    _('Update map statistics'),
    _('Reproject raster map from different GRASS location'),
    _('Tiling'),
    _('Produces tilings of the source projection for use in the destination region and projection.'),
    _('Manage colors'),
    _('Color tables'),
    _('Color tables (stddev)'),
    _("Sets color rules based on stddev from a raster map's mean value."),
    _('Manage color rules interactively'),
    _('Interactive management of raster color tables.'),
    _('Export color table'),
    _('Blend 2 color rasters'),
    _('Blends color components of two raster maps by a given ratio.'),
    _('Create RGB'),
    _('RGB to HIS'),
    _('Query raster maps'),
    _('Query values by coordinates'),
    _('Query colors by value'),
    _('Map type conversions'),
    _('Raster to vector'),
    _('Raster series to 3D raster'),
    _('Raster 2.5D to 3D raster'),
    _('Raster buffers and distance'),
    _('Buffer rasters'),
    _('Concentric circles'),
    _('Closest points'),
    _('Grow by one cell'),
    _('Generates a raster map layer with contiguous areas grown by one cell.'),
    _('Distance to features'),
    _('Mask'),
    _('Creates a MASK for limiting raster operation.'),
    _('Raster map calculator'),
    _('Raster map calculator'),
    _('Neighborhood analysis'),
    _('Moving window'),
    _('Neighborhood points'),
    _('Overlay rasters'),
    _('Cross product'),
    _('Patch raster maps'),
    _('Raster series aggregation'),
    _('Raster series accumulation'),
    _('Statistical overlay'),
    _('Quantiles overlay'),
    _('Solar radiance and shadows'),
    _('LatLong map'),
    _('Solar irradiance and irradiation'),
    _('Shadows map'),
    _('Sunshine hours and solar angles'),
    _('Terrain analysis'),
    _('Generate contour lines'),
    _('Cost surface'),
    _('Cumulative movement costs'),
    _('Least cost route or flow'),
    _('Compute shaded relief'),
    _('Apply shade to raster'),
    _('Drapes a color raster over an shaded relief or aspect map.'),
    _('Slope and aspect'),
    _('Terrain parameters'),
    _('Textural features'),
    _('Visibility'),
    _('Distance to features'),
    _('Horizon angle'),
    _('Transform features'),
    _('Clump'),
    _('Grow'),
    _('Generates a raster map layer with contiguous areas grown by one cell.'),
    _('Thin'),
    _('Hydrologic modeling'),
    _('Carve stream channels'),
    _('Fill lake'),
    _('Depressionless map and flowlines'),
    _('Flow accumulation'),
    _('Flow lines'),
    _('Watershed analysis'),
    _('Watershed subbasins'),
    _('Watershed basin creation'),
    _('Extraction of stream networks'),
    _('SIMWE Overland flow modeling'),
    _('SIMWE Sediment flux modeling'),
    _('Topographic index map'),
    _('TOPMODEL simulation'),
    _('USLE K-factor'),
    _('USLE R-factor'),
    _('Groundwater modeling'),
    _('Groundwater flow'),
    _('Groundwater solute transport'),
    _('Landscape patch analysis'),
    _('Set up sampling and analysis framework'),
    _("Configuration editor for r.li.'index'"),
    _('Edge density'),
    _('Contrast weighted edge density'),
    _('Patch area mean'),
    _('Patch area range'),
    _('Patch area Std Dev'),
    _('Patch area Coeff Var'),
    _('Patch density'),
    _('Patch number'),
    _("Dominance's diversity"),
    _("Shannon's diversity"),
    _("Simpson's diversity"),
    _('Richness'),
    _('Shape index'),
    _('Wildfire modeling'),
    _('Rate of spread'),
    _('Least-cost spread paths'),
    _('Anisotropic spread simulation'),
    _('Change category values and labels'),
    _('Manage category information'),
    _('Interactively edit category values'),
    _('Edits cell values in a raster map.'),
    _('Reclassify by size'),
    _('Reclasses a raster map greater or less than user specified area size (in hectares).'),
    _('Reclassify'),
    _('Recode'),
    _('Rescale'),
    _('Rescale with histogram'),
    _('Generate random cells'),
    _('Random cells'),
    _('Random cells and vector points'),
    _('Generate surfaces'),
    _('Fractal surface'),
    _('Gaussian kernel density surface'),
    _('Gaussian deviates surface'),
    _('Plane'),
    _('Creates raster plane map given dip (inclination), aspect (azimuth) and one point.'),
    _('Random deviates surface'),
    _('Random surface with spatial dependence'),
    _('Interpolate surfaces'),
    _('Bilinear and bicubic from vector points'),
    _('IDW from raster points'),
    _('IDW from vector points'),
    _('Raster contours'),
    _('Regularized spline tension'),
    _('Raster series interpolation'),
    _('Ordinary or block kriging'),
    _('Performs ordinary or block kriging.'),
    _('Fill NULL cells'),
    _('Fills no-data areas in raster maps using spline interpolation.'),
    _('Reports and statistics'),
    _('Basic raster metadata'),
    _('Manage category information'),
    _('General statistics'),
    _('Quantiles for large data sets'),
    _('Range of category values'),
    _('Sum area by raster map and category'),
    _('Statistics for clumped cells'),
    _('Total corrected area'),
    _('Univariate raster statistics'),
    _('Sample transects'),
    _('Sample transects (bearing/distance)'),
    _('Covariance/correlation'),
    _('Linear regression'),
    _('Multiple regression'),
    _('Mutual category occurrences'),
    _('&Vector'),
    _('Develop vector map'),
    _('Create new vector map'),
    _('Create new empty vector map'),
    _('Edit vector map (non-interactively)'),
    _('Convert object types'),
    _('Parallel lines'),
    _('Dissolve boundaries'),
    _('Dissolves boundaries between adjacent areas sharing a common category number or attribute.'),
    _('Create 3D vector over raster'),
    _('Extrude 3D vector map'),
    _('Create labels'),
    _('Reposition vector map'),
    _('Rectify vector map'),
    _('Reproject vector map from different GRASS location'),
    _('Support file maintenance'),
    _('Topology maintenance'),
    _('Create or rebuild topology'),
    _('Rebuild topology on all vector maps'),
    _('Rebuilds topology on all vector maps in the current mapset.'),
    _('Build polylines'),
    _('Split lines'),
    _('Split polylines'),
    _('Clean vector map'),
    _('Toolset for cleaning topology of vector map.'),
    _('Smooth or simplify'),
    _('Add centroids'),
    _('Adds missing centroids to closed boundaries.'),
    _('Manage colors'),
    _('Color tables'),
    _('Manage color rules interactively'),
    _('Interactive management of vector color tables.'),
    _('Export color table'),
    _('Query vector map'),
    _('Query with coordinate(s)'),
    _('Query vector attribute data'),
    _('Feature selection'),
    _('Select by attributes'),
    _('Select by another map'),
    _('Map type conversions'),
    _('Vector to raster'),
    _('Vector to 3D raster'),
    _('2D vector to 3D vector'),
    _('Buffer vectors'),
    _('Lidar analysis'),
    _('Identify and remove outliers'),
    _('Detect edges'),
    _('Detect interiors'),
    _('Correct and reclassify objects'),
    _('Linear referencing'),
    _('Create LRS'),
    _('Create stationing'),
    _('Create points/segments'),
    _('Find line id and offset'),
    _('Nearest features'),
    _('Network analysis'),
    _('Vector network analysis tool'),
    _('Tool for interactive vector network analysis.'),
    _('Network preparation'),
    _('Allocate subnets'),
    _('Split net'),
    _('Shortest path'),
    _('Shortest path for sets of features'),
    _('Shortest path using timetables'),
    _('Shortest path for all pairs'),
    _('Visibility network'),
    _('Bridges and articulation points'),
    _('Maximum flow'),
    _('Vertex connectivity'),
    _('Components'),
    _('Centrality'),
    _('Steiner tree'),
    _('Minimum spanning tree'),
    _('Traveling salesman analysis'),
    _('Overlay vector maps'),
    _('Overlay vector maps'),
    _('Patch vector maps'),
    _('Manage categories'),
    _('Change or report categories'),
    _('Reclassify'),
    _('Update attributes'),
    _('Update area attributes from raster'),
    _('Calculates univariate statistics from a raster map based on a vector map and uploads statistics to new attribute columns.'),
    _('Update area attributes from vector'),
    _('Update point attributes from areas'),
    _('Uploads vector values at positions of vector points to the table.'),
    _('Update database values from vector'),
    _('Sample raster maps at point locations'),
    _('Sample raster neighborhood around points'),
    _('Generate area for current region'),
    _('Generate areas from points'),
    _('Convex hull'),
    _('Delaunay triangles'),
    _('Voronoi diagram/Thiessen polygons'),
    _('Generate grid'),
    _('Generate points'),
    _('Generate from database'),
    _('Generate points along lines'),
    _('Generate random points'),
    _('Perturb points'),
    _('Remove outliers in point sets'),
    _('Test/training point sets'),
    _('Reports and statistics'),
    _('Basic vector metadata'),
    _('Classify attribute data'),
    _('Report topology by category'),
    _('Reports geometry statistics for vector maps.'),
    _('Univariate attribute statistics for points'),
    _('Univariate statistics for attribute columns'),
    _('Calculates univariate statistics on selected table column for a GRASS vector map.'),
    _('Quadrat indices'),
    _('Test normality'),
    _('&Imagery'),
    _('Develop images and groups'),
    _('Create/edit group'),
    _('Creates, edits, and lists groups of imagery files.'),
    _('Target group'),
    _('Mosaic images'),
    _('Mosaics several images and extends colormap.'),
    _('Manage image colors'),
    _('Color balance for RGB'),
    _('Performs auto-balancing of colors for RGB images.'),
    _('HIS to RGB'),
    _('RGB to HIS'),
    _('Rectify image or raster'),
    _('Histogram'),
    _('Generate histogram of image'),
    _('Spectral response'),
    _('Displays spectral response at user specified locations in group or images.'),
    _('Pan sharpening'),
    _('Image fusion algorithms to sharpen multispectral with high-res panchromatic channels'),
    _('Classify image'),
    _('Clustering input for unsupervised classification'),
    _('Input for supervised MLC'),
    _('Maximum likelihood classification (MLC)'),
    _('Interactive input for supervised classification'),
    _('Generates spectral signatures by allowing the user to outline training areas.'),
    _('Input for supervised SMAP'),
    _('Sequential maximum a posteriori classification (SMAP)'),
    _('Object segmentation'),
    _('Filter image'),
    _('Edge detection'),
    _('Matrix/convolving filter'),
    _('Transform image'),
    _('Canonical correlation'),
    _('Principal components'),
    _('Fast Fourier'),
    _('Inverse Fast Fourier'),
    _('Satellite images tools'),
    _('Aster DN to radiance/reflectance'),
    _('Landsat DN to radiance/reflectance'),
    _('Landsat cloud cover assessment'),
    _('Modis quality control'),
    _('Atmospheric correction'),
    _('Topographic correction'),
    _('Satellite images products'),
    _('Vegetation indices'),
    _('Tasseled cap vegetation index'),
    _('Performs Tasseled Cap (Kauth Thomas) transformation.'),
    _('Albedo'),
    _('Emissivity'),
    _('Biomass growth'),
    _('Evapotranspiration calculation'),
    _('Instantaneaous Net Radiation'),
    _('Soil heat flux'),
    _('Sensible heat flux'),
    _('Evaporative fraction'),
    _('Actual Evapotranspiration'),
    _('Temporal integration of ETa'),
    _('Hargreaves methods Evapotranspiration'),
    _('Penman-Monteith Evapotranspiration'),
    _('Priestley-Taylor Evapotranspiration'),
    _('Reports and statistics'),
    _('Kappa analysis'),
    _('OIF for LandSat TM'),
    _('Calculates Optimum-Index-Factor table for spectral bands'),
    _('3D r&aster'),
    _('Develop 3D raster map'),
    _('Manage 3D NULL values'),
    _('Manage timestamp'),
    _('Print/add/remove a timestamp for a 3D raster map'),
    _('Map type conversions'),
    _('3D rasters to raster series'),
    _('3D color tables'),
    _('Export 3D color table'),
    _('3D mask'),
    _('3D raster map calculator'),
    _('3D raster map calculator'),
    _('Cross section'),
    _('Groundwater modeling'),
    _('Interpolate 3D raster from points'),
    _('Reports and Statistics'),
    _('Basic 3D raster metadata'),
    _('3D raster statistics'),
    _('Univariate statistics for 3D rasters'),
    _('&Database'),
    _('Database information'),
    _('List databases'),
    _('Lists all databases for a given driver and location.'),
    _('List drivers'),
    _('Lists all database drivers.'),
    _('List tables'),
    _('Lists all tables for a given database.'),
    _('Describe table'),
    _('Describes a table in detail.'),
    _('List columns'),
    _('List all columns for a given table.'),
    _('Manage databases'),
    _('Connect'),
    _('Prints/sets general DB connection for current mapset.'),
    _('Login'),
    _('Sets user/password for DB driver/database.'),
    _('Create database'),
    _('Creates an empty database.'),
    _('Drop database'),
    _('Removes an existing database.'),
    _('Drop table'),
    _('Drops an attribute table.'),
    _('Copy table'),
    _("Copy a table. Either 'from_table' (optionally with 'where') can be used or 'select' option, but not 'from_table' and 'select' at the same time."),
    _('Drop column'),
    _('Drops a column from selected attribute table.'),
    _('Test'),
    _('Test database driver, database must exist and set by db.connect.'),
    _('Query'),
    _('Query any table'),
    _('Selects data from attribute table. Performs SQL query statement(s).'),
    _('Query vector attribute data'),
    _('SQL statement'),
    _("Executes any SQL statement. For SELECT statements use 'db.select'."),
    _('Vector database connections'),
    _('New table'),
    _('Creates and connects a new attribute table to a given layer of an existing vector map.'),
    _('Remove table'),
    _('Removes existing attribute table of a vector map.'),
    _('Join table'),
    _('Joins a database table to a vector map table.'),
    _('Add columns'),
    _('Adds one or more columns to the attribute table connected to a given vector map.'),
    _('Drop column'),
    _('Drops a column from the attribute table connected to a given vector map.'),
    _('Rename column'),
    _('Renames a column in the attribute table connected to a given vector map.'),
    _('Change values'),
    _('Updates a column in the attribute table connected to a vector map.'),
    _('Drop row'),
    _('Removes a vector feature from a vector map through attribute selection.'),
    _('Reconnect vectors to database'),
    _('Reconnects attribute tables for all vector maps from the current mapset to a new database.'),
    _('Set vector map - database connection'),
    _('&Temporal'),
    _('Manage datasets'),
    _('Create'),
    _('Rename'),
    _('Remove'),
    _('Update metadata'),
    _('Merge'),
    _('Temporally shift'),
    _('Snap maps of dataset'),
    _('List'),
    _('Manage maps in datasets'),
    _('Register maps in datasets'),
    _('Unregister maps from datasets'),
    _('List raster dataset maps'),
    _('List vector dataset maps'),
    _('List 3D raster dataset maps'),
    _('Import'),
    _('Import raster dataset'),
    _('Import vector dataset'),
    _('Export'),
    _('Export raster dataset'),
    _('Export raster dataset as VTK time series'),
    _('Export vector dataset'),
    _('Convert raster dataset to 3D raster'),
    _('Extraction'),
    _('Extract subset of raster dataset'),
    _('Extract subset of vector dataset'),
    _('Extract subset of 3D raster dataset'),
    _('Query vector dataset attribute data'),
    _('Raster dataset color table'),
    _('Raster calculations'),
    _('3D raster calculations'),
    _('Interpolate gaps in raster datasets'),
    _('Aggregation'),
    _('Neighborhood analysis in raster dataset'),
    _('Aggregation in raster datasets'),
    _('Temporal aggregation'),
    _('Temporal aggregation by dataset'),
    _('Sampling'),
    _('Temporal sampling'),
    _('Query raster dataset by vector points dataset'),
    _('Observe specific locations in raster dataset'),
    _('Reports and statistics'),
    _('Space time datasets metadata'),
    _('Univariate raster dataset statistics'),
    _('Univariate vector dataset statistics'),
    _('Univariate 3D raster dataset statistics'),
    _('Report temporal topology'),
    _('GUI tools'),
    _('Animation tool'),
    _('Launch animation tool.'),
    _('Timeline tool'),
    _('Plot temporal extents.'),
    _('Temporal plot tool'),
    _('Plot temporal values.'),
    _('GUI tools'),
    _('Animation tool'),
    _('Launch animation tool.'),
    _('Attribute table manager'),
    _('Georectify'),
    _('Manage Ground Control Points for Georectification'),
    _('Graphical modeler'),
    _('Launch Graphical modeler'),
    _('Interactive input for supervised classification'),
    _('Generates spectral signatures by allowing the user to outline training areas.'),
    _('Map Swipe'),
    _('Launch Map Swipe'),
    _('Cartographic Composer'),
    _('Launch Cartographic Composer'),
    '']
menustrings_menudata.ModelerMenuData = [
    _('&File'),
    _('New'),
    _('Create new model'),
    _('Open'),
    _('Load model from file'),
    _('Save'),
    _('Save model'),
    _('Save as'),
    _('Save model to file'),
    _('Close'),
    _('Close model file'),
    _('Export to image'),
    _('Export model to image'),
    _('Export to Python'),
    _('Export model to Python script'),
    _('Quit modeler'),
    _('Close modeler window'),
    _('&Settings'),
    _('Preferences'),
    _('Modeler settings'),
    _('&Model'),
    _('Add command'),
    _('Add action (GRASS command) to model'),
    _('Add data'),
    _('Add data item to model'),
    _('Define relation'),
    _('Define relation between data and action items'),
    _('Add loop / series'),
    _('Adds loop (series) to model'),
    _('Add comment'),
    _('Adds comment to model'),
    _('Remove item'),
    _('Remove action/data from model'),
    _('Model properties'),
    _('Model properties (name, purpose, etc.)'),
    _('Delete intermediate data'),
    _('Delete intermediate data defined in the model'),
    _('Run model'),
    _('Run entire model'),
    _('Validate model'),
    _('Validate entire model'),
    _('&Help'),
    _('Help'),
    _('Display the HTML man pages of Graphical modeler'),
    _('About Graphical Modeler'),
    _('Display information about Graphical Modeler'),
    '']
menustrings_menudata.PsMapMenuData = [
    _('&File'),
    _('Page setup'),
    _('Specify paper size, margins and orientation'),
    _('Load instruction file'),
    _('Load text file with mapping instructions'),
    _('Export instruction file'),
    _('Generate text file with mapping instructions'),
    _('Export to PostScript'),
    _('Generate PostScript output'),
    _('Export to PDF'),
    _('Generate PDF output'),
    _('Launch ps.map dialog'),
    _('Launch ps.map dialog'),
    _('Quit'),
    _('Close Cartographic Composer'),
    _('&Insert'),
    _('Map frame'),
    _('Add or edit map frame'),
    _('Raster map'),
    _('Add or edit raster map'),
    _('Vector map'),
    _('Add or edit vector map'),
    _('Map legend'),
    _('Add or edit raster and vector legend'),
    _('Map info'),
    _('Add or edit map info'),
    _('Scale bar'),
    _('Add or edit scale bar'),
    _('Text'),
    _('Add text'),
    _('Image'),
    _('Add image'),
    _('North Arrow'),
    _('Add north arrow'),
    _('Delete'),
    _('Delete selected object'),
    _('&Help'),
    _('Help'),
    _('Display the HTML man pages of Cartographic Composer'),
    _('About Cartographic Composer'),
    _('Display information about Cartographic Composer'),
    '']
